Health checks on Ray Deployments
bracket-ai/elevaite-inference-rayservice pull request #21
Opened 2024-12-17 19:58 UTC by korinayo

Adds basic health check functionality that runs every 30s. Callable via inference API.

2024-12-17 20:42 UTC, dienhartd reviewed
one sanity check question otherwise lgtm

2024-12-17 20:42 UTC, dienhartd commented on llama_vision.py
> +            self._clear_cache()
sanity check: does `_clear_cache()` every 30s affect anything else as a side effect or just this route?

2024-12-17 20:53 UTC, korinayo commented on llama_vision.py
> +            self._clear_cache()
affects the model object hosted at this deployment as well.

2024-12-18 22:21 UTC, boyleconnor commented on mini_cpm.py
> +    def check_health(self):
Do I understand that Ray guarantees that `deployment`s will have their `check_health()` method called automatically (on a user-defined period)? The [documentation](https://docs.ray.io/en/latest/serve/api/doc/ray.serve.deployment_decorator.html) seems to imply as much, but in a very off-handed sort of way, without much detail.

2024-12-18 22:21 UTC, boyleconnor commented on transformers_model.py
> +                    self.pipe("Is this thing on?")
I'm not confident that these two formats cover all potential `task` schemas. Are you, @korinayo?

2024-12-18 22:58 UTC, boyleconnor commented
Have you tested this? One way to do so would be to create a branch in `elevaite` (branched off `main`) with the [`DEFAULT_WORKING_DIR`](https://github.com/bracket-ai/elevaite/blob/a9ad6e39bd6b9fa31dcf293660d7ad5fc201801b/elevaite/rayservice_utils.py#L30) named constant changed to this branch (or even better, a specific commit thereof). You could also change the test logic to add a call to `/health` (e.g. around [here](https://github.com/bracket-ai/elevaite/blob/a9ad6e39bd6b9fa31dcf293660d7ad5fc201801b/tests/e2e/test_web_server.py#L97))

2024-12-19 16:56 UTC, korinayo commented on mini_cpm.py
> +    def check_health(self):
Yep -- called automatically. 10s intervals is default.

2024-12-19 17:34 UTC, korinayo commented on transformers_model.py
> +                    self.pipe("Is this thing on?")
Not confident -- was biasing too heavily to current use cases. Updated

2024-12-19 17:35 UTC, korinayo commented
> Have you tested this? One way to do so would be to create a branch in `elevaite` (branched off `main`) with the [`DEFAULT_WORKING_DIR`](https://github.com/bracket-ai/elevaite/blob/a9ad6e39bd6b9fa31dcf293660d7ad5fc201801b/elevaite/rayservice_utils.py#L30) named constant changed to this branch (or even better, a specific commit thereof). You could also change the test logic to add a call to `/health` (e.g. around [here](https://github.com/bracket-ai/elevaite/blob/a9ad6e39bd6b9fa31dcf293660d7ad5fc201801b/tests/e2e/test_web_server.py#L97))

have tested on the on prem test cluster @boyleconnor

2024-12-20 01:21 UTC, boyleconnor requested changes

2024-12-20 01:21 UTC, boyleconnor commented on transformers_model.py
> +            return {"status": "healthy"}
In the case where `task != "text-generation"`, can you change `"status"` to `"unknown"` (I'm assuming Ray will just check the status code/whether the method completes without raising an exception).

If that doesn't work (i.e. a different value of `status` causes the health check result to be misinterpreted as unhealthy), can you try adding another key to this dictionary such as `"info"` with a message such as `f"warning: task '{self.task}' does not currently have a working health check"`.

Basically, I'd like there to be some indication that this health check is not doing what it promises to do.

2024-12-20 01:21 UTC, boyleconnor commented on transformers_model.py
> +                detail="Endpoint is unhealthy. Basic model.pipe() call failed.",
Nitpick: the call isn't to `self.model.pipe()`, it is to `self.pipe()`. This should say something like `Basic inference call failed.`

2024-12-20 01:21 UTC, boyleconnor commented on transformers_model.py
> +            return
Putting this outside the `try...except...finally` block means that the cache won't be cleared during health check calls; is this the desired behavior?

2024-12-20 01:21 UTC, boyleconnor commented on transformers_model.py
> +            return
Actually, I can't tell if this is intended to return "healthy" by default for non-text-generation endpoints, or "unhealthy"

2024-12-20 01:21 UTC, boyleconnor commented on transformers_model.py
> +            return {"status": "healthy"}
^this comment is premised on the assumption that we return "healthy" by default for all non-text-generation tasks. Ignore if that is not true

2024-12-20 05:34 UTC, korinayo commented on transformers_model.py
> +            return
@boyleconnor  It returns nothing! The health check serves a dual purpose here. 

- For Ray: any code that returns an error message will cause a failed Ray health check that will change the status of the deployment. Returning nothing will trigger neither pass nor failure. 
- For elevaite: Binu requested something that returns a health status for the endpoint if we know it. I think your request for an "unknown" status is correct for this purpose. As is the response body would be empty. If we can't replicate the call structure of the model then the endpoint could very well be healthy and we wouldn't know.

2024-12-20 05:37 UTC, korinayo commented on transformers_model.py
> +            return {"status": "healthy"}
the assumption is incorrect, but the warning message is a good idea.

2024-12-20 05:42 UTC, boyleconnor commented on transformers_model.py
> +            return
Ah, thanks for the clarification. Thiis is resolved, assuming [this warning message](https://github.com/bracket-ai/elevaite-inference-rayservice/pull/21#discussion_r1893495370) gets implemented

2024-12-20 05:47 UTC, korinayo commented on transformers_model.py
> +                    self.pipe("Is this thing on?")
further update here: have manually tested all of elevaite's [supported tasks](https://github.com/bracket-ai/elevaite/blob/main/elevaite/models.py#L8-L23) and come up with a set that work out of the box with this current pipe(text) call. We will run this version of the health check for all deployments w/ pipelines of these tasks. I will create an issue to figure out how to expand others (if feasible). For now this covers pretty much every current elevaite use case we've

2024-12-23 19:40 UTC, boyleconnor approved these changes

2024-12-23 19:41 UTC, boyleconnor commented
@korinayo hold on, I think you should bump the version number in `pyproject.toml`

2024-12-23 20:10 UTC, korinayo commented
> @korinayo hold on, I think you should bump the version number in `pyproject.toml`

thank you! done!

2024-12-23 20:10 UTC, merged

2025-01-08 01:44 UTC, boyleconnor commented on transformers_model.py
> +                self.pipe("Is this thing on?", max_new_tokens=10)
This `max_new_tokens` should only be there for `text-generation` models. Fixing this in #22