pass dtype to model creation
bracket-ai/elevaite-inference-rayservice pull request #9
Opened 2024-10-02 17:21 UTC by korinayo

2024-10-04 17:39 UTC, boyleconnor requested changes
Before I review this in depth, I want to get a better idea of what the overall goal of this PR is (see comments)

2024-10-04 17:39 UTC, boyleconnor commented on mini_cpm.py
> +
I'd like to see some explanation (in the PR conversation + in comments & docstrings) of why we're now manually calling garbage collection and even allowing the client to trigger that action.

Will we now expect the user to do that in certain situations?

2024-10-04 17:39 UTC, boyleconnor commented on transformers_model.py
> +        }
It seems like the purpose of this PR is much broader than just "pass dtype to model creation"; I get the impression that you're clearing the way for us to do inference more effectively on CPU-only nodes

2024-10-04 18:13 UTC, korinayo commented on mini_cpm.py
> +
so part of the problem with inference reliability is that across requests CPU/GPU memory isn't getting freed, which causes inference to fail after sufficiently many requests. This is a measure to forcefully free the memory under the (safe) assumption that inference calls are independent (we're not serving chatbots).

The /clear_cache endpoint is mostly for my dev purposes. I am running into an issue where as failed requests pile up, the amount of memory available on GPU decreases. This is a way to force it to free up and will remove it when I grok what's going on on a deeper level.

2024-10-04 18:14 UTC, korinayo commented on transformers_model.py
> +        }
It is broad, and you are correct that I am clearing the way for us to do inference on CPU only nodes, but i am also addressing some GPU related issues in the process (see above comment)

2024-10-04 18:20 UTC, korinayo commented
@boyleconnor you're correct to point out the broadness of this PR. It is trying to achieve the following. 
- allow us to serve models on CPU only, which is a feature request from Binu. 
- decrease the size of the models hosted on RAM, be that CPU or GPU, by specifying the correct dtype that matches the dtype in the model config, if available. 
- forcefully clear the CUDA, and CPU cache across inference requests. 

Let me know if you have any more questions.

2024-10-04 18:35 UTC, dienhartd commented on mini_cpm.py
> +
Was memory pressure the real issue instead of the small increase in characters?

2024-10-04 18:38 UTC, dienhartd commented
Edits seems reasonable - might want to conditionally enable cache clearing on a debug mode / dev deploy and maybe put it in a `/dev` route but would be at our discretion for now before prod deploys. `TODO:` for that would be nice tho

2024-10-04 18:52 UTC, korinayo commented on mini_cpm.py
> +
i think it was yeah -- this PR also adds better logging and HTTP exceptions and the errors are pretty consistently  of the form

```
500 -- Response: {"detail":"CUDA out of memory. Tried to allocate 15.75 GiB. GPU 0 has a total capacity of 44.31 GiB of which 15.66 GiB is free. Process 1468 has 0 bytes memory in use. Of the allocated memory 27.12 GiB is allocated by PyTorch, and 1.02 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)"}
```

2024-10-06 08:51 UTC, korinayo commented
> Edits seem reasonable - might want to conditionally enable cache clearing on a debug mode / dev deploy and maybe put it in a `/dev` route but would be at our discretion for now before prod deploys. `TODO:` for that would be nice tho

@dienhartd just took it out for now.

2024-10-16 17:37 UTC, boyleconnor commented on mini_cpm.py
> +            )
We should never send unfiltered internal messages to the client

2024-10-16 17:40 UTC, boyleconnor commented on sentence_transformers_model.py
> +            model_args["model_kwargs"] = model_kwargs
Hard to come up with non-confusing variable names given Huggingface's param naming strategy. Maybe rename `model_args` to `sentence_transformer_kwargs`.

2024-10-16 17:40 UTC, boyleconnor commented on sentence_transformers_model.py
> +            )
Don't send internal error messages to the user (security risk)

2024-10-16 17:42 UTC, boyleconnor commented on sentence_transformers_model.py
> +        args["torch_dtype"],
Just to double check, you are committing on the `elevaite` web server side to always send all of these `args`, right?

2024-10-16 17:42 UTC, boyleconnor commented on transformers_model.py
> +            )
Don't send internal error messages to the user (bad security)

2024-10-16 17:43 UTC, boyleconnor commented on utils.py
> +}
I'm a bit surprised `torch` doesn't provide a way to do this

2024-10-17 19:04 UTC, korinayo commented on sentence_transformers_model.py
> +        args["torch_dtype"],
Yep! It is float32 by default.

2024-10-17 19:15 UTC, korinayo commented on utils.py
> +}
none that i'm aware of (or that a quick google has surfaced)

2024-10-17 19:34 UTC, korinayo commented on sentence_transformers_model.py
> +            model_args["model_kwargs"] = model_kwargs
@boyleconnor to what end?

2024-10-17 19:37 UTC, korinayo commented on sentence_transformers_model.py
> +            model_args["model_kwargs"] = model_kwargs
is it because there's both `model_args` and `model_kwargs`?

2024-10-17 19:39 UTC, korinayo commented on sentence_transformers_model.py
> +            model_args["model_kwargs"] = model_kwargs
changed

2024-10-17 19:40 UTC, korinayo commented
> Sorry, @korinayo, I put this off for a bit because I don't know enough to say whether what you are doing with garbage collection is prudent or not. It makes me a bit nervous, but if you are confident that this is the right way to get better performance/stability, I'll take your word for it.
> 
> There are some other changes I did request, though

@boyleconnor The cache clearing is very important. The python gc.collect() call less so now. Removed and I think we are good to go

2024-10-17 20:26 UTC, boyleconnor approved these changes
I nitpicked your multiple calls to `_clear_cache()` but I suppose you are probably just erring on the side of making sure the cache gets cleared, no matter what. Is that right?

I think I've said this before, but I don't know much about the logic of `torch.cuda.empty_cache()` and I am assuming that you know what you're doing

2024-10-17 20:26 UTC, boyleconnor commented on transformers_model.py
> +        self.pipe = pipeline(**pipe_kwargs)
Good find

2024-10-17 20:26 UTC, boyleconnor commented on mini_cpm.py
> +            self._clear_cache()
Do you need to call `_clear_cache()` here if it gets called in the `finally` block no matter what?

2024-10-17 20:26 UTC, boyleconnor commented on mini_cpm.py
> +            self._clear_cache()
Ditto here on calling `_clear_cache()` (when it gets called in `finally` too)

2024-10-17 20:26 UTC, boyleconnor commented on transformers_model.py
> +            self._clear_cache()
Seems like this would result in at least two calls to `_clear_cache()` no matter what

2024-10-17 22:19 UTC, merged